# categories.py

# Dicionário para as descrições das categorias
CATEGORY_DESCRIPTIONS = {
    'Load Operations': 'Operations related to loading values into variables.',
    'Arithmetic and Logical Operations': 'Operations performing arithmetic or logical manipulations.',
    'Comparison Operations': 'Operations that perform comparisons.',
    'Type Checking Operations': 'Operations for checking the type of variables.',
    'Conditional Operations': 'Operations for conditional evaluations.',
    'Control Flow Statements': 'Statements that alter the flow of control in the program.',
    'Function Definitions': 'Operations related to defining functions.',
    'Function Calls': 'Operations for calling functions.',
    'Class Definitions': 'Operations related to defining classes.',
    'Method Calls': 'Operations for calling methods of objects.',
    'Object Operations': 'Operations related to creating and manipulating objects.',
    'Property Operations': 'Operations on properties of objects.',
    'Variable Declarations': 'Operations for declaring variables.',
    'String Operations': 'Operations related to manipulating strings.',
    'Exception Handling': 'Operations for handling exceptions.',
}

# Dicionário para as categorias das operações
OPERATION_CATEGORIES = {
    'LoadString': 'Load Operations',
    'LoadFloat': 'Load Operations',
    'LoadInteger': 'Load Operations',
    'LoadBoolean': 'Load Operations',
    'LoadGlobal': 'Load Operations',
    'LoadRegExp': 'Load Operations',
    'LoadBigInt': 'Load Operations',
    'LoadThis': 'Load Operations',
    'LoadNull': 'Load Operations',
    'LoadUndefined': 'Load Operations',
    'BinaryOperation': 'Arithmetic and Logical Operations',
    'UnaryOperation': 'Arithmetic and Logical Operations',
    'Compare': 'Comparison Operations',
    'TypeOf': 'Type Checking Operations',
    'TernaryOperation': 'Conditional Operations',
    'BeginFor': 'Control Flow Statements',
    'EndFor': 'Control Flow Statements',
    'BeginWhileLoop': 'Control Flow Statements',
    'EndWhileLoop': 'Control Flow Statements',
    'BeginIf': 'Control Flow Statements',
    'EndIf': 'Control Flow Statements',
    'BeginSwitch': 'Control Flow Statements',
    'EndSwitch': 'Control Flow Statements',
    'BeginTry': 'Control Flow Statements',
    'EndTry': 'Control Flow Statements',
    'BeginCatch': 'Control Flow Statements',
    'EndCatch': 'Control Flow Statements',
    'BeginFinally': 'Control Flow Statements',
    'EndFinally': 'Control Flow Statements',
    'BeginFunction': 'Function Definitions',
    'EndFunction': 'Function Definitions',
    'CallFunction': 'Function Calls',
    'Return': 'Function Definitions',
    'BeginClassDefinition': 'Class Definitions',
    'EndClassDefinition': 'Class Definitions',
    'BeginConstructor': 'Class Definitions',
    'EndConstructor': 'Class Definitions',
    'CallMethod': 'Method Calls',
    'CallComputedMethod': 'Method Calls',
    'CallMethodWithSpread': 'Method Calls',
    'Construct': 'Object Operations',
    'CreateIntArray': 'Object Operations',
    'CreateFloatArray': 'Object Operations',
    'CreateArray': 'Object Operations',
    'CreateArrayWithSpread': 'Object Operations',
    'SetProperty': 'Property Operations',
    'GetProperty': 'Property Operations',
    'SetElement': 'Property Operations',
    'GetElement': 'Property Operations',
    'UpdateProperty': 'Property Operations',
    'UpdateElement': 'Property Operations',
    'DeleteProperty': 'Property Operations',
    'DeleteElement': 'Property Operations',
    'ConfigureProperty': 'Property Operations',
    'ConfigureElement': 'Property Operations',
    'UpdatePrivateProperty': 'Property Operations',
    'Yield': 'Control Flow Statements',
    'BeginForInLoop': 'Control Flow Statements',
    'BeginClassStaticSetter': 'Class Definitions',
    'ConfigureComputedProperty': 'Property Operations',
    'BeginArrowFunction': 'Function Definitions',
    'DefineNamedVariable': 'Variable Declarations',
    'BeginBlockStatement': 'Control Flow Statements',
    'EndClassInstanceSetter': 'Class Definitions',
    'UpdateSuperProperty': 'Property Operations',
    'BeginForLoopAfterthought': 'Control Flow Statements',
    'Dup': 'Arithmetic and Logical Operations',
    'GetSuperProperty': 'Property Operations',
    'TestInstanceOf': 'Comparison Operations',
    'BeginClassPrivateStaticMethod': 'Class Definitions',
    'EndAsyncFunction': 'Function Definitions',
    'EndGeneratorFunction': 'Function Definitions',
    'EndClassConstructor': 'Class Definitions',
    'CallFunctionWithSpread': 'Function Calls',
    'BeginAsyncArrowFunction': 'Function Definitions',
    'BeginAsyncFunction': 'Function Definitions',
    'EndObjectLiteral': 'Object Operations',
    'BeginClassInstanceSetter': 'Class Definitions',
    'EndPlainFunction': 'Function Definitions',
    'UpdateComputedProperty': 'Property Operations',
    'DestructArray': 'Object Operations',
    'LoadBuiltin': 'Load Operations',
    'ClassAddPrivateStaticProperty': 'Class Definitions',
    'GetComputedProperty': 'Property Operations',
    'EndObjectLiteralComputedMethod': 'Object Operations',
    'BeginElse': 'Control Flow Statements',
    'BeginAsyncGeneratorFunction': 'Function Definitions',
    'BeginSwitchDefaultCase': 'Control Flow Statements',
    'DestructObject': 'Object Operations',
    'LoopBreak': 'Control Flow Statements',
    'Update': 'Arithmetic and Logical Operations',
    'BeginForOfLoop': 'Control Flow Statements',
    'EndCodeString': 'String Operations',
    'EndDoWhileLoop': 'Control Flow Statements',
    'BeginForLoopInitializer': 'Control Flow Statements',
    'YieldEach': 'Control Flow Statements',
    'BeginSwitchCase': 'Control Flow Statements',
    'SetSuperProperty': 'Property Operations',
    'BeginObjectLiteralComputedMethod': 'Object Operations',
    'CallSuperMethod': 'Method Calls',
    'BeginRepeatLoop': 'Control Flow Statements',
    'BeginObjectLiteralMethod': 'Object Operations',
    'EndForInLoop': 'Control Flow Statements',
    'EndClassStaticGetter': 'Class Definitions',
    'StoreNamedVariable': 'Variable Declarations',
    'EndBlockStatement': 'Control Flow Statements',
    'BeginClassInstanceGetter': 'Class Definitions',
    'ObjectLiteralAddElement': 'Object Operations',
    'ClassAddStaticElement': 'Class Definitions',
    'BeginClassStaticMethod': 'Class Definitions',
    'EndForLoop': 'Control Flow Statements',
    'BeginGeneratorFunction': 'Function Definitions',
    'BeginClassStaticInitializer': 'Class Definitions',
    'BeginWhileLoopHeader': 'Control Flow Statements',
    'GetPrivateProperty': 'Property Operations',
    'BeginClassPrivateInstanceMethod': 'Class Definitions',
    'SwitchBreak': 'Control Flow Statements',
    'EndArrowFunction': 'Function Definitions',
    'EndObjectLiteralGetter': 'Object Operations',
    'EndObjectLiteralSetter': 'Object Operations',
    'ClassAddStaticProperty': 'Class Definitions',
    'ObjectLiteralAddProperty': 'Object Operations',
    'BeginDoWhileLoopHeader': 'Control Flow Statements',
    'ConstructWithSpread': 'Object Operations',
    'ObjectLiteralSetPrototype': 'Object Operations',
    'DeleteComputedProperty': 'Property Operations',
    'EndWith': 'Control Flow Statements',
    'BeginClassStaticGetter': 'Class Definitions',
    'ObjectLiteralAddComputedProperty': 'Object Operations',
    'EndTryCatchFinally': 'Control Flow Statements',
    'BeginForOfLoopWithDestruct': 'Control Flow Statements',
    'BeginObjectLiteralSetter': 'Object Operations',
    'EndAsyncArrowFunction': 'Function Definitions',
    'BeginForLoopBody': 'Control Flow Statements',
    'EndClassPrivateInstanceMethod': 'Class Definitions',
    'BeginDoWhileLoopBody': 'Control Flow Statements',
    'BeginCodeString': 'String Operations',
    'EndAsyncGeneratorFunction': 'Function Definitions',
    'DestructObjectAndReassign': 'Object Operations',
    'CallComputedMethodWithSpread': 'Method Calls',
    'BeginWith': 'Control Flow Statements',
    'DestructArrayAndReassign': 'Object Operations',
    'EndSwitchCase': 'Control Flow Statements',
    'LoadArguments': 'Load Operations',
    'Reassign': 'Variable Declarations',
    'ObjectLiteralCopyProperties': 'Object Operations',
    'EndClassStaticInitializer': 'Class Definitions',
    'BeginPlainFunction': 'Function Definitions',
    'ClassAddPrivateInstanceProperty': 'Class Definitions',
    'CallSuperConstructor': 'Class Definitions',
    'ClassAddInstanceElement': 'Class Definitions',
    'EndClassInstanceMethod': 'Class Definitions',
    'BeginForLoopCondition': 'Control Flow Statements',
    'EndObjectLiteralMethod': 'Object Operations',
    'ClassAddInstanceComputedProperty': 'Class Definitions',
    'CallPrivateMethod': 'Method Calls',
    'EndClassInstanceGetter': 'Class Definitions',
    'SetComputedProperty': 'Property Operations',
    'BeginObjectLiteralGetter': 'Object Operations',
    'Await': 'Control Flow Statements',
    'LoadNamedVariable': 'Load Operations',
    'BeginClassInstanceMethod': 'Class Definitions',
    'ClassAddStaticComputedProperty': 'Class Definitions',
    'ClassAddInstanceProperty': 'Class Definitions',
    'ThrowException': 'Exception Handling',
    'BeginClassConstructor': 'Class Definitions',
    'BeginObjectLiteral': 'Object Operations',
    'BeginWhileLoopBody': 'Control Flow Statements',
    'EndClassPrivateStaticMethod': 'Class Definitions',
    'EndClassStaticMethod': 'Class Definitions',
    'CreateTemplateString': 'String Operations',
    'EndRepeatLoop': 'Control Flow Statements',
    'EndClassStaticSetter': 'Class Definitions',
    'TestIn': 'Comparison Operations',
    'EndForOfLoop': 'Control Flow Statements',
    'LoopContinue': 'Control Flow Statements',
    'SetPrivateProperty': 'Property Operations'
}
