import pandas as pd

def generate_latex_content(grouped_df, overall_summary_df, plot_data, config):
    latex_content = r"""
    \documentclass{article}
    \usepackage{graphicx}
    \usepackage{booktabs}
    \usepackage{pgfplots}
    \pgfplotsset{compat=1.17}
    \begin{document}

    \title{%s}
    \author{Generated by Streamlit}
    \date{\today}
    \maketitle

    \section{Overall Summary Statistics}
    \begin{tabular}{ll}
    \toprule
    Metric & Value \\
    \midrule
    """ % config.get('report_title', 'Analysis Report')
    
    for index, row in overall_summary_df.iterrows():
        latex_content += f"{row['Metric']} & {row['Value']} \\\\ \n"
    
    latex_content += r"""
    \bottomrule
    \end{tabular}

    \section{Grouped Operation Statistics by Category}
    \begin{tabular}{llllll}
    \toprule
    Category & Description & 1 Count & 1000 Count & 1 Mean & 1000 Mean \\
    \midrule
    """
    
    for index, row in grouped_df.iterrows():
        latex_content += f"{row['Category']} & {row['Category Description']} & {row['1 Count']} & {row['1000 Count']} & {row['1 Mean']} & {row['1000 Mean']} \\\\ \n"
    
    latex_content += r"""
    \bottomrule
    \end{tabular}

    \section{%s}
    \begin{tikzpicture}
    \begin{axis}[
        width=%s,
        height=%s,
        xlabel={%s},
        ylabel={%s},
        xtick={%s},
        xticklabels={%s},
        ymajorgrids=true,
        grid style=dashed,
        x tick label style={rotate=90, anchor=east},
    ]
    """ % (
        config.get('plot_section_title', 'Plot Section'),
        config.get('plot_width', '1.2\\textwidth'),
        config.get('plot_height', '0.6\\textheight'),
        config.get('xlabel', 'Category'),
        config.get('ylabel', 'Average Values'),
        ', '.join(map(str, range(1, len(plot_data['categories']) + 1))),
        ', '.join([f"{{{cat}}}" for cat in plot_data['categories']])
    )

    latex_content += r"""
    \addplot[
        ybar,
        bar width=.4cm,
        fill=blue,
        draw=blue,
        mark=none,
    ] coordinates {"""
    
    for i, (cat, mean1) in enumerate(zip(plot_data['categories'], plot_data['means_1']), 1):
        latex_content += f"({i}, {mean1}) "
    
    latex_content += r"""};

    \addplot[
        ybar,
        bar width=.4cm,
        fill=red,
        draw=red,
        mark=none,
    ] coordinates {"""
    
    for i, (cat, mean1000) in enumerate(zip(plot_data['categories'], plot_data['means_1000']), 1):
        latex_content += f"({i}, {mean1000}) "
    
    latex_content += r"""};
    
    \legend{%s, %s}
    \end{axis}
    \end{tikzpicture}

    \end{document}
    """ % (
        config.get('legend_label1', "Fuzzilli's Programs"),
        config.get('legend_label2', "JSTargetFuzzer's Programs")
    )
    
    return latex_content

def save_latex_file(grouped_df, overall_summary_df, plot_data, config, file_path="report.tex"):
    latex_content = generate_latex_content(grouped_df, overall_summary_df, plot_data, config)
    with open(file_path, "w") as f:
        f.write(latex_content)
